# DP Global configuration
# See config.default.yml for default values

collector:
  export:
    google_spread_sheet:
      # The sheet it will read from in your drive
      source_name:  "Fading Suns"
      # The sheet it will write to in your drive
      #target_name:  "Fading Suns Crashtest"
      target_name: "Fading Suns"
      # Your google service credential file (do not forget to share the spreadsheets source_name and TARGET_NAME with the email address...)
      credentials:  "cartograph/creds.json"
      # The tab used in the spreadsheet
      tab:          "Characters"
      tab_abstract: "Abstract"
