# -- DEPLOY_ON_PI.yml playbook --
# To use postgresql plugins, do not forget to install community general with the line:
#   ansible-galaxy collection install community.general
#   ansible-galaxy collection install community.postgresql
# Launch this playbook with :
#   ansible-playbook -i hosts deploy_on_pi.yml --verbose
#
---
- name: Deployment on Raspberry PI 3B+
  hosts: pi
  gather_facts: no
  remote_user: root
  become: yes
  tasks:
    - name: Add EPEL repository for armhfp
      yum_repository:
        name: epel_release_armhfp
        description: Epel release for armhfp
        baseurl: https://armv7.dev.centos.org/repodir/epel-pass-1/
        enabled: yes
        gpgcheck: no
        state: present

    - name: Installing all packages
      yum:
        name:
          - vim
          - git
          - zsh
          - wget
          - libffi-devel
          - httpd
          - ntp
          - python36
          - python3-pip
          - postgresql
          - postgresql-devel
          - mod_wsgi
          - python-psycopg2
          - python3-devel
          - gcc-c++
          - libjpeg
          - libjpeg-devel
        state: present
        update_cache: yes
    - name: Clone DP repo
      git:
        repo: 'https://github.com/zaffarelli/dramatis_personae.git'
        dest: /opt/srv/dp/
        clone: yes
        update: no
    - name: Checkout DP repo
      git:
        repo: 'https://github.com/zaffarelli/dramatis_personae.git'
        dest: /opt/srv/dp/
        version: master
        update: no

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Initialize postgresql database
      command: "service postgresql initdb"

    - name: Start postgresql
      service:
        name: postgresql
        state: started
        enabled: yes
#    - name: Create postgresql user dp
#      community.general.postgresql_user:
#        name: dp
#        password: dp
#        encrypted: yes
#
#    - name: Create postgresql database dramatis_personae
#      community.general.postgresql_db:
#        name: dramatis_personae
#        owner: dp
#
#    - name: Write the apache config file
#      file:
#        src: /srv/dramatis_personae/scripts/deploy/httpd_dp.conf
#        dest: /etc/httpd/conf.d/httpd_dp.conf
#        state: hard
#    - name: Start httpd
#      service:
#        name: httpd
#        state: restarted
#        enabled: yes

...